/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.entidade.Funcionarios;
import view.estabelecimentos.ListaEstabelecimentos;
import view.funcionario.ListaFuncionarios;
import view.servicos.TelaSelecionaEstabelecimento;

/**
 *
 * @author ronan
 */
public class TelaEntrada extends javax.swing.JFrame {
    
    public Funcionarios usr;

    /**
     * Creates new form TelaPrincipal
     *
     * @param uLogin
     */
    public TelaEntrada(Funcionarios uLogin) {
        initComponents();
        // coloca uma figura na barra de título da janela
//        URL url = this.getClass().getResource("/img/store.png");
//        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
//        this.setIconImage(imagemTitulo);
        usr = uLogin;
        lblUsuario.setText("Seja bem vindo " + usr.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuEstabelecimentos = new javax.swing.JMenuItem();
        mnuFuncionarios = new javax.swing.JMenuItem();
        mnuServicos = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenuItem();
        mnuConvenios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuEntradas = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenu();
        mnuTrocaSenha = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Comercial");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setText("Nome do Usuário");

        jMenu1.setText("Cadastros");

        mnuEstabelecimentos.setText("Estabelecimentos");
        mnuEstabelecimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEstabelecimentosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEstabelecimentos);

        mnuFuncionarios.setText("Funcionários");
        mnuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuFuncionarios);

        mnuServicos.setText("Serviços");
        mnuServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuServicosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuServicos);

        mnuClientes.setText("Clientes");
        jMenu1.add(mnuClientes);

        mnuConvenios.setText("Convênios");
        jMenu1.add(mnuConvenios);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimentação");

        mnuEntradas.setText("Painel de Gestão");
        mnuEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEntradasActionPerformed(evt);
            }
        });
        jMenu2.add(mnuEntradas);

        jMenuItem5.setText("Financeiro");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");
        jMenuBar1.add(jMenu3);

        mnuSair.setText("Sistema");

        mnuTrocaSenha.setText("Trocar Senha");
        mnuTrocaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTrocaSenhaActionPerformed(evt);
            }
        });
        mnuSair.add(mnuTrocaSenha);

        jMenuItem7.setText("Sair");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnuSair.add(jMenuItem7);

        jMenuBar1.add(mnuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(710, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEstabelecimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEstabelecimentosActionPerformed
        ListaEstabelecimentos tela = new ListaEstabelecimentos();
        tela.setVisible(true);
    }//GEN-LAST:event_mnuEstabelecimentosActionPerformed

    private void mnuTrocaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTrocaSenhaActionPerformed

    }//GEN-LAST:event_mnuTrocaSenhaActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void mnuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFuncionariosActionPerformed
        ListaFuncionarios tela = new ListaFuncionarios();
        tela.setVisible(true);
    }//GEN-LAST:event_mnuFuncionariosActionPerformed

    private void mnuServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuServicosActionPerformed
        TelaSelecionaEstabelecimento tela = new TelaSelecionaEstabelecimento(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_mnuServicosActionPerformed

    private void mnuEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEntradasActionPerformed

    }//GEN-LAST:event_mnuEntradasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEntrada(new Funcionarios()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuConvenios;
    private javax.swing.JMenuItem mnuEntradas;
    private javax.swing.JMenuItem mnuEstabelecimentos;
    private javax.swing.JMenuItem mnuFuncionarios;
    private javax.swing.JMenu mnuSair;
    private javax.swing.JMenuItem mnuServicos;
    private javax.swing.JMenuItem mnuTrocaSenha;
    // End of variables declaration//GEN-END:variables
}
