/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.pessoas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Pessoas;
import model.dao.PessoasDAO;

/**
 *
 * @author AVELL
 */
public class ListaPessoas extends javax.swing.JFrame {

    /**
     * Creates new form ListaPessoas
     */
    public ListaPessoas() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTablePessoas.getModel();
        jTablePessoas.setRowSorter(new TableRowSorter<TableModel>(modelo));

        readJTable();
    }

    public void readJTable() {
        String tipo;
        DefaultTableModel modelo = (DefaultTableModel) jTablePessoas.getModel();
        modelo.setNumRows(0);
        PessoasDAO pDAO = new PessoasDAO();

        for (Pessoas p : pDAO.read()) {
            if (p.getTipo() == 'F') {
                tipo = "Física";
            } else {
                tipo = "Jurídica";
            }
            modelo.addRow(new Object[]{
                p.getIdpessoa(),
                p.getNome(),
                tipo,
                p.getDoc_fed(),
                p.getCidade(),
                p.getEmail(),
                p.getTel_fixo(),
                p.getTel_cel()
            });
        }
    }

    public void readForFind() {
        String tipo;
        String busca = txtFind.getText();
        String campo[] = new String[8];
        DefaultTableModel modelo = (DefaultTableModel) jTablePessoas.getModel();
        modelo.setNumRows(0);
        PessoasDAO pDAO = new PessoasDAO();

        campo[0] = "idpessoa";
        campo[1] = "nome";
        campo[2] = "tipo";
        campo[3] = "doc_fed";
        campo[4] = "cidade";
        campo[5] = "email";
        campo[6] = "tel_fixo";
        campo[7] = "tel_cel";

        for (Pessoas p : pDAO.readForFind(campo[cboFind.getSelectedIndex()], busca)) {
            if (p.getTipo() == 'F') {
                tipo = "Física";
            } else {
                tipo = "Jurídica";
            }
            modelo.addRow(new Object[]{
                p.getIdpessoa(),
                p.getNome(),
                tipo,
                p.getDoc_fed(),
                p.getCidade(),
                p.getEmail(),
                p.getTel_fixo(),
                p.getTel_cel()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePessoas = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cboFind = new javax.swing.JComboBox<>();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Listagem de Pessoas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jTablePessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Tipo", "Doc. Federal", "Cidade", "E-mail", "Tel. Fixo", "Tel. Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePessoas);
        if (jTablePessoas.getColumnModel().getColumnCount() > 0) {
            jTablePessoas.getColumnModel().getColumn(0).setMinWidth(80);
            jTablePessoas.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTablePessoas.getColumnModel().getColumn(0).setMaxWidth(80);
            jTablePessoas.getColumnModel().getColumn(2).setMinWidth(80);
            jTablePessoas.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTablePessoas.getColumnModel().getColumn(2).setMaxWidth(80);
            jTablePessoas.getColumnModel().getColumn(3).setMinWidth(130);
            jTablePessoas.getColumnModel().getColumn(3).setPreferredWidth(130);
            jTablePessoas.getColumnModel().getColumn(3).setMaxWidth(130);
            jTablePessoas.getColumnModel().getColumn(6).setMinWidth(130);
            jTablePessoas.getColumnModel().getColumn(6).setPreferredWidth(130);
            jTablePessoas.getColumnModel().getColumn(6).setMaxWidth(130);
            jTablePessoas.getColumnModel().getColumn(7).setMinWidth(130);
            jTablePessoas.getColumnModel().getColumn(7).setPreferredWidth(130);
            jTablePessoas.getColumnModel().getColumn(7).setMaxWidth(130);
        }

        btnCreate.setBackground(new java.awt.Color(0, 204, 51));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreate.setText("Novo");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 204, 0));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Alterar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("Excluir");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cboFind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboFind.setForeground(new java.awt.Color(0, 0, 204));
        cboFind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "Tipo Pessoa", "Doc. Federal", "Cidade", "E-mail", "Tel. Fixo", "Tel. Celular", " " }));

        txtFind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFind.setForeground(new java.awt.Color(0, 51, 204));

        btnFind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFind.setText("Buscar");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                        .addComponent(cboFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(cboFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        CadastroPessoa cp = new CadastroPessoa();
        cp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (jTablePessoas.getSelectedRow() != -1 && jTablePessoas.getSelectedRowCount() == 1) {
            AlterarPessoa au = new AlterarPessoa((int) jTablePessoas.getValueAt(jTablePessoas.getSelectedRow(), 0));
            au.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro para alterar... \n"
                    + "Escolha apenas um único registro !!!", "Sistema Comercial", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (jTablePessoas.getSelectedRow() != -1 && jTablePessoas.getSelectedRowCount() == 1) {
            int option = JOptionPane.showConfirmDialog(null, "Deseja realmete excluir o registro ?", "Sistema Comercial", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                PessoasDAO uDAO = new PessoasDAO();

                if (uDAO.delete((int) jTablePessoas.getValueAt(jTablePessoas.getSelectedRow(), 0))) {
                    readJTable();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro para alterar... \n"
                    + "Escolha apenas um único registro !!!", "Sistema Comercial", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        readForFind();
    }//GEN-LAST:event_btnFindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPessoas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePessoas;
    private javax.swing.JTextField txtFind;
    // End of variables declaration//GEN-END:variables
}
